### ISSUE TITLE
how do you login?

### ISSUE THREAD

**Issue by gmaijoe** [devxoul/graygram-ios#2]
sorry if basic

**Comment by devxoul** [comment]
You can use test account:

ID: `test`
PW: `test`

**Comment by zhoupIT** [comment]
A server with the specified hostname could not be found

**Comment by devxoul** [comment]
@zhoupIT, a server is down at this time. It costs $7 per month so I only run during my lecture. I just added this english notice in README.

**Comment by zhoupIT** [comment]
Get it!Thanks!
